version: '3.6'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: sepp
      POSTGRES_DB: sepp
    ports:
      - 5432:5432
    volumes: 
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
